# Generated by Django 2.0.1 on 2018-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restNet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.CharField(default='test', max_length=9000),
            preserve_default=False,
        ),
    ]
